# Generated by build script - contains embedded license data
# This file is compiled into .so, so it will always be included in the package

# Embedded license data (base64 encoded, matches the .dat/.bin files)
LICENSE_DATA = {
    "sys_info": "dVZkODFTRHhZcjFuY2ZFYnB1aUx1aE1wTzZEYnJ0bzRFeTA9",
    "sys_backup": "dVZkODFTRHhZcjFuY2ZFYnB1aUx1aE1wTzZEYnJ0bzRFeTA9",
    "cache_info": "dVZkODFTRHhZcjFuY2ZFYnB1aUx1aE1wTzZEYnJ0bzRFeTA9",
}

def get_license_data(key):
    """Get license data by key"""
    return LICENSE_DATA.get(key, "")
